services:
    oro_magento_contact_us.embedded_form:
        class: Oro\Bundle\MagentoContactUsBundle\Form\Type\ContactRequestType
        arguments:
             - '@oro_locale.helper.default_locale_localization'
        tags:
            - { name: oro_embedded_form, label: oro.magentocontactus.embedded_form.label, type: Oro\Bundle\MagentoContactUsBundle\Form\Type\ContactRequestType }
            - { name: form.type, alias: oro_magento_contactus_contact_request }

    oro_magento_contact_us.contact_request.form:
        class: Symfony\Component\Form\Form
        factory: ['@form.factory', createNamed]
        arguments:
            - "oro_magento_contactus_contact_request"
            - Oro\Bundle\MagentoContactUsBundle\Form\Type\ContactRequestType
            - null

    oro_magento_contact_us.datagrid.helper:
         class: Oro\Bundle\MagentoContactUsBundle\Datagrid\ContactRequestDatagridHelper
         tags:
             - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.before.orcrm-contact-requests-grid-extended, method: buildBefore }
